### ISSUE TITLE
看看这个，不知道咋点出来的。

### ISSUE THREAD

**Issue by parcool** [woshidasusu/base-module#1]
```
java.lang.IllegalStateException: The current thread must have a looper!
     at android.view.Choreographer$1.initialValue(Choreographer.java:102)
     at android.view.Choreographer$1.initialValue(Choreographer.java:97)
     at java.lang.ThreadLocal$Values.getAfterMiss(ThreadLocal.java:430)
     at java.lang.ThreadLocal.get(ThreadLocal.java:65)
     at android.view.Choreographer.getInstance(Choreographer.java:232)
     at android.view.RenderNodeAnimator$DelayedAnimationHelper.<init>(RenderNodeAnimator.java:437)
     at android.view.RenderNodeAnimator.getHelper(RenderNodeAnimator.java:421)
     at android.view.RenderNodeAnimator.end(RenderNodeAnimator.java:254)
     at android.graphics.drawable.RippleComponent$RenderNodeAnimatorSet.end(RippleComponent.java:334)
     at android.graphics.drawable.RippleComponent.endHardwareAnimations(RippleComponent.java:237)
     at android.graphics.drawable.RippleComponent.draw(RippleComponent.java:160)
     at android.graphics.drawable.RippleDrawable.drawBackgroundAndRipples(RippleDrawable.java:899)
     at android.graphics.drawable.RippleDrawable.draw(RippleDrawable.java:700)
     at android.view.View.drawBackground(View.java:16409)
     at android.view.View.draw(View.java:16208)
     at android.view.View.draw(View.java:16129)
     at android.view.ViewGroup.drawChild(ViewGroup.java:3612)
     at androidx.coordinatorlayout.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1246)
     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3402)
     at android.view.View.draw(View.java:16127)
     at android.view.ViewGroup.drawChild(ViewGroup.java:3612)
     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3402)
     at android.view.View.draw(View.java:16127)
     at android.view.ViewGroup.drawChild(ViewGroup.java:3612)
     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3402)
     at android.view.View.draw(View.java:16127)
     at android.view.ViewGroup.drawChild(ViewGroup.java:3612)
     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3402)
     at android.view.View.draw(View.java:16127)
     at android.view.ViewGroup.drawChild(ViewGroup.java:3612)
     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3402)
     at android.view.View.draw(View.java:16127)
     at android.view.ViewGroup.drawChild(ViewGroup.java:3612)
     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3402)
     at android.view.View.draw(View.java:16127)
     at android.view.ViewGroup.drawChild(ViewGroup.java:3612)
     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3402)
     at android.view.View.draw(View.java:16127)
     at android.view.ViewGroup.drawChild(ViewGroup.java:3612)
     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3402)
     at android.view.View.draw(View.java:16127)
     at android.view.ViewGroup.drawChild(ViewGroup.java:3612)
     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3402)
     at android.view.View.draw(View.java:16127)
     at android.view.ViewGroup.drawChild(ViewGroup.java:3612)
     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3402)
     at android.view.View.draw(View.java:16220)
     at com.android.internal.policy.PhoneWindow$DecorView.draw(PhoneWindow.java:2690)
     at com.dasu.blur.BlurHelper.getViewBitmap(BlurHelper.java:122)
     at com.dasu.blur.BlurHelper.calculateSourceBitmap(BlurHelper.java:103)
     at com.dasu.blur.BlurHelper.access$000(BlurHelper.java:28)
     at com.dasu.blur.BlurHelper$1.run(BlurHelper.java:36)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
     at java.lang.Thread.run(Thread.java:818)
```

**Comment by woshidasusu** [comment]
@parcool 
非常感谢反馈~
我抽时间查看一下

**Comment by parcool** [comment]
@woshidasusu BlurHelper中第122行，改用这样吧！```
view.post(new Runnable() {
            @Override
            public void run() {
                view.draw(canvas);
            }
        });
```
我调试了好久才发现，这个可能导致我这边崩溃。

**Comment by woshidasusu** [comment]
我早上也测试了下，发现你给的日志是说在子线程中执行view.draw会出异常，但我这边一直没复现，所以还不清楚原因~
切到主线程做应该是没问题，我再查一查看
谢谢~

**Comment by woshidasusu** [comment]
@parcool

**Comment by woshidasusu** [comment]
@parcool 
你那边是必现的话，能否提供下设备的系统版本，型号之类的信息呢。
或者你执行下 adb shell getprop，将信息发给我看一下，我看能否找个类似的设备复现一下看看。

**Comment by woshidasusu** [comment]
@parcool 
哈喽，可以请你用新版本 0.0.6 再试一下会不会有这么问题么
看了下异常堆栈信息，感觉应该是涉及到硬件加速画背景的问题，这个过程需要使用到 Choreographer，而这个需要有个队列辅助，所以在子线程中运行会出问题。
目前有两种解决思路：
1. 关闭硬件加速
2. 子线程创建队列
0.0.6 版本是尝试在子线程中创建队列，用完就删掉，但我这边没复现这个问题，所以不清楚可行不，你有时间的话，可以试一下新版本看看还会有问题存在哈~

如果还是不行的话，那我再尝试另一种方案看看。

**Comment by parcool** [comment]
@woshidasusu 这边不是必然复现，由于项目也赶进度，bug这些后面再来看了。。。。
